import './globals.css'

import type { Metadata } from 'next'

import Providers from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-Br" suppressHydrationWarning={true}>
      <body cz-shortcut-listen="true">
        <div className="flex h-full flex-col overflow-hidden">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  )
}
