-- CreateEnum
CREATE TYPE "IconCardType" AS ENUM ('CARTEIRA', 'NUBANK', 'BB', 'ITAU', 'SICREDI', 'BRADESCO', 'SANTANDER', 'CAIXA', 'INTER', 'C6BANK', 'NEXT', 'NEON', 'PAN', 'PICPAY', 'INFINITYPAY', 'ITI', 'MERCADOPAGO', 'PAGSEGURO');

-- AlterTable
ALTER TABLE "Card" ADD COLUMN     "icon" "IconCardType" NOT NULL DEFAULT 'CARTEIRA';
